### ISSUE TITLE
Weird default value

### ISSUE THREAD

**Issue by donbeave** [werf/kubedog#144]
Hello!

Just saw a strange message:

```bash
kubedog help

  -t, --timeout int            Timeout of operation in seconds. 0 is wait forever. Default is 0. (default -1)

```

`Default is 0. (default -1)` this part looks weird to me, not clear what value will be used by default.

**Comment by distorhead** [comment]
This is totally messed up.

Actually it is `-1` by default and `-1` means "wait forever".

**Comment by ilya-lesikov** [comment]
Just a typo. Also, we will deprecate Kubedog CLI in the future to focus on it as an easily embedded library. For out-of-the-box CLI experience we recommend using [werf](https://github.com/werf/werf). Later we will also release [Nelm](https://github.com/werf/nelm) as a standalone binary as a direct Helm replacement with Kubedog built-in.
