### ISSUE TITLE
Print final status table in multitracker

### ISSUE THREAD

**Issue by distorhead** [werf/kubedog#166]
Final status table should resemble status-progress table and helm final table with all resources with pods listed. Do not print child resources (too verbose).

**Comment by ilya-lesikov** [comment]
Since introduction of [dynamic tracker](https://github.com/werf/kubedog/tree/9e5c458d11bb9effd9ca49bda70f826857d0b681/pkg/trackers/dyntracker) this logic must be implemented outside of kubedog by the library user.
