### ISSUE TITLE
Implement show logs until modes

### ISSUE THREAD

**Issue by distorhead** [werf/kubedog#168]
Kubedog show logs until: ControllerIsDone|PodIsDone(default)|EndOfDeployProcess.

For now it is always PodIsDone, add more modes.

**Comment by ilya-lesikov** [comment]
Too complex (requires low-level trackers refactoring), too little value. Does not fit in the Task paradigm of Dynamic Tracker, where we stop further processing as soon as task is completed. Won't implement.
