### ISSUE TITLE
Fail fast when resource readiness probe failed

### ISSUE THREAD

**Issue by distorhead** [werf/kubedog#169]
Kubedog should handle fails of readiness-probes as errors and fail tracking. For now these fails only printed to log.

There should be statuses of child pods in the status-reports of non-ready controllers.

There is info about readiness-probes failures in the pod's status in conditions fields.

**Comment by Tom910** [comment]
I had the same case. When port hadn't correctly setting. As a result helm freeze on 5 minutes and kubedog did not show any events\logs about problem

**Comment by dudicoco** [comment]
@distorhead are there any plans to implement this?

Currently we cannot use kubedog as we have also found out that it does not detect readiness gate failures

**Comment by distorhead** [comment]
@dudicoco Hi! We have plans to implement support for all kinds of probes. We have already digged a lot in this direction. Maybe this will be implemented by the end of august, but not certain.

**Comment by dudicoco** [comment]
Thanks @distorhead , looking forward to the new additions :)

**Comment by dudicoco** [comment]
@distorhead thanks for the new additions!

When can we expect a new kubedog release?
