### ISSUE TITLE
Fallback tracker for unsupported resources kinds

### ISSUE THREAD

**Issue by distorhead** [werf/kubedog#182]
Fallback tracker should work similarly to `kubectl wait --for condition=Ready`. Maybe import kubectl wait code as a first step.

**Comment by distorhead** [comment]
Seems like there is no common conditions. Each resource kind have own set of conditions. Need more research which conditions is suitable for kubedog rollout tracker for each resource kind.

**Comment by ilya-lesikov** [comment]
Done in https://github.com/werf/kubedog/pull/255
