### ISSUE TITLE
Elimination tracker should wait until Namespace is being "Terminated"

### ISSUE THREAD

**Issue by distorhead** [werf/kubedog#186]
Simple delete namespace then wait until get request gives "not exists" not working. Maybe there is some option for the get-request to show terminating resources.

https://github.com/werf/kubedog/blob/master/pkg/trackers/elimination/elimination.go#L139

**Comment by ilya-lesikov** [comment]
[Dynamic Tracker](https://github.com/werf/kubedog/blob/298b80cd9cd899ee18e1bf6da3df4357034eda0d/pkg/trackers/dyntracker/dynamic_absence_tracker.go) obsoletes all the other trackers, including this one. This problem most likely fixed in the new Dynamic Absence Tracker.
