### ISSUE TITLE
In Jenkins, kubedog output format is too confusing

### ISSUE THREAD

**Issue by skycyan** [werf/kubedog#189]
# Configure in Jenkins:
### kubedog multitrack, The output format is too confusing

![18160426](https://user-images.githubusercontent.com/53815445/102590467-97333400-414b-11eb-92bb-73f828731f02.png)

**Comment by JanisOrlovs** [comment]
Hello,
Use in-conjuction with xtrem plugin. All will be ok

**Comment by alexey-igrychev** [comment]
@skycyan In recent versions, this output problem has been fixed.
