### ISSUE TITLE
Move Binaries off of Bintray

### ISSUE THREAD

**Issue by zgriesinger** [werf/kubedog#199]
Hi!

We noticed today that the bintray link for downloading KubeDog (and bintray as a whole) is going away on May 1st, is there plan to migrate the KubeDog binaries off of bintray to a different platform?

In the mean time can install the CLI from source, however the curl from bintray was convenient.

More info on Bintray sunsetting:
https://status.bintray.com/
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by distorhead** [comment]
Yep, we will move binaries to s3-compatible storage. We have already moved werf and mulitiwerf binaries, kubedog is on the way.

**Comment by kuzaxak** [comment]
Any news about that?

**Comment by shurup** [comment]
Oh sorry. It was actually fixed a few days ago (via #201), so, please welcome to use the updated links in README.

**Comment by zgriesinger** [comment]
@shurup will there be a GitHub release for v0.5.0 (including SHA256SUMs)? I only see them for v0.4.0

https://github.com/werf/kubedog/releases

**Comment by shurup** [comment]
@zgriesinger oh sorry, my fault… @alexey-igrychev will make it today.

**Comment by alexey-igrychev** [comment]
The release [v0.5.0](https://github.com/werf/kubedog/releases/tag/v0.5.0) is done.
