### ISSUE TITLE
Older releases can't be downloaded anymore

### ISSUE THREAD

**Issue by antoinerg** [werf/kubedog#203]
Earlier releases that are hosted on bintray.com are not accessible anymore:
![Selection_004](https://user-images.githubusercontent.com/301546/118030617-89b55b00-b333-11eb-8697-7a2ad2424be5.png)

Would it be possible to host them somewhere else?

Thank you!

**Comment by alexey-igrychev** [comment]
Hi, @antoinerg 

If I understand correctly, all links are working until July 4.

It's not hard for us to move the binaries to another storage, but could you tell why you need the old versions, why not just switch to the latest one?

**Comment by josegonzalez** [comment]
Latest version changes its logging output, so it's not ideal to use in an existing system.

I've vendored a copy of 0.3.4 [here](https://github.com/dokku/dokku-scheduler-kubernetes/releases/tag/0.17.6) for now in case anyone needs it.

**Comment by antoinerg** [comment]
> why not just switch to the latest one?

Basically to ensure reproducibility.

> I've vendored a copy of 0.3.4 here for now in case anyone needs it.

Awesome! Thanks @josegonzalez
