### ISSUE TITLE
pod names are cut off in status progress

### ISSUE THREAD

**Issue by dudicoco** [werf/kubedog#228]
Within the status progress, the pod names are always cut off:

```sh
 ┌ Status progress
 │ STATEFULSET                                                                    REPLICAS       READY           UP-TO-DATE
 │ prometheus-server                                                              2/2            1->2            2
 │ │   POD                           READY      RESTARTS       STATUS
 │ ├── server-0                      3/3        1              Running
 │ └── server-1                      3/3        1              Running
```

**Comment by ilya-lesikov** [comment]
Formatting is not a responsibility of Kubedog anymore, with new Dynamic Tracker it is up to the user to get data from Storage, which is populated by [Dynamic Tracker](https://github.com/werf/kubedog/tree/298b80cd9cd899ee18e1bf6da3df4357034eda0d/pkg/trackers/dyntracker), then format it and print it however he likes. Reference Formatter implementation available in [Nelm](https://github.com/werf/nelm/tree/6375703101bf30c3332125fe6aa9f7be00f7b9e2/pkg/track) and it shows resource names in full.
