### ISSUE TITLE
debug  multitrack use goland

### ISSUE THREAD

**Issue by sjfbjs** [werf/kubedog#243]
how can i debug  multitrack use  goland ?

![image](https://user-images.githubusercontent.com/24262176/151113336-08eef0f5-e62b-4cb8-be8b-73214f95c603.png)

**Comment by distorhead** [comment]
Hi! Could you give more details about the problem?

Is it a problem with passing multitrack configuration specs into kubedog stdin from goland? Then it would be suitable to add kubedog cli param to accept configuration from some file.

**Comment by ilya-lesikov** [comment]
We will deprecate Kubedog CLI in the future to focus on it as an easily embedded library. For out-of-the-box CLI experience we recommend using [werf](https://github.com/werf/werf). Later we will also release [Nelm](https://github.com/werf/nelm) as a standalone binary as a direct Helm replacement with Kubedog built-in.
