### ISSUE TITLE
Consider changing pods logs appearance for better UX

### ISSUE THREAD

**Issue by distorhead** [werf/kubedog#244]
Colorize pods logs or change log-block appearance to highlight logging block and separate it from status-progress block and other info.

**Comment by ilya-lesikov** [comment]
With new Dynamic Tracker formatting is not a responsibility of Kubedog anymore. Although reference Formatter implementation in [Nelm](https://github.com/werf/nelm/tree/6375703101bf30c3332125fe6aa9f7be00f7b9e2/pkg/track) already formats log blocks properly.
