### ISSUE TITLE
Rework multitracker

### ISSUE THREAD

**Issue by distorhead** [werf/kubedog#286]
Multitracker should be renamed to something like `LoggerMultitracker`. Also implement common part of multitracker so that logger/printing logic reside on top of some base multitracker. Use only new reworked lowlevel resources trackers in this new multitracker (see https://github.com/werf/kubedog/issues/285).

**Comment by zhilyaev** [comment]
Oh yeah

**Comment by ilya-lesikov** [comment]
Implemented as the new [Dynamic Tracker](https://github.com/werf/kubedog/pull/313), which will obsolete Multitracker. Printer implementation can be found at https://github.com/werf/nelm

Low-level trackers kept as they are for now.
