### ISSUE TITLE
Add support for custom types as generic

### ISSUE THREAD

**Issue by davidglia** [werf/kubedog#311]
### Description of the issue:
We're trying to track status of kind [Tables](https://github.com/aws-controllers-k8s/dynamodb-controller) using kubedog. 

```
        echo "\$tableManifest" | yq -o=json '.
          | map({
              "Name":.metadata.name,
              "Namespace":"default",
              "GroupVersionKind":{"Kind":"Table","Group":"dynamodb.services.k8s.aws","Version":"v1alpha1"},
              "AllowFailuresCount":5,
              "ShowServiceMessages":true
            })
            | {"Generics": .}' \
        | kubedog multitrack --kube-context dev
```

The problem is it is not returning logs. This is an example of the status of a Table, which we expect to see included in the logs.

```
Status:
  Ack Resource Metadata:
    Arn:               
    Owner Account ID: 
    Region:            us-west-2
  Conditions:
    Last Transition Time:  2023-08-23T10:42:28Z
    Message:               Resource synced successfully
    Reason:
    Status:                True
    Type:                  ACK.ResourceSynced
  Creation Date Time:      2023-08-01T11:20:30Z
  Item Count:              9158
  Table ID:                
  Table Size Bytes:        
  Table Status:            ACTIVE
```

We found out that the reason why it is not logging anything is because `Type: ACK.ResourceSynced` is not supported. 

### Proposal:
Is it possible to introduce the following changes:

- Support type as generic
- Add ability to forward condition from a json. This is how it is [defined](https://github.com/aws-controllers-k8s/dynamodb-controller/blob/996e68b94e08c707b57f9c64ada940c963654043/pkg/resource/table/conditions.go#L62-L78) in the AWS controller.

**Comment by ilya-lesikov** [comment]
Currently Generic tracker tries to find an appropriate condition in the resource status based on heuristic algorithm, and condition with such a name (ACK.ResourceSynced) is pretty rare. Obviously, we can't hardcode every possible condition for every Custom Resource out there. A mechanism to pass a custom condition for a specific resource sounds reasonable, we'll implement it in the future.

**Comment by ilya-lesikov** [comment]
We heavily improved status detection for custom resources. Also, if status cannot be detected automatically, we encourage users to send us PR with their custom condition added to [this yaml file](https://github.com/werf/kubedog/blob/main/pkg/tracker/generic/contrib_resource_status_rules.yaml).
