### ISSUE TITLE
Watch pod that does not exist fails with timeout by default

### ISSUE THREAD

**Issue by distorhead** [werf/kubedog#52]
Default timeout is -1, which should disable timeouts.
Check timeouts, make fixes.

**Comment by diafour** [comment]
`follow` mode works as expected — wait forever.

`rollout track` timeout problem is reproducible with results similar to that in tg discussion:
```
$ time ./kubedog rollout track -n qqq pod asd      
error tracking Pod `asd` in namespace `qqq`: timed out tracking resource
timed out tracking resource
./kubedog rollout track -n qqq pod asd  0,04s user 0,02s system 0% cpu 5:00,02 total
```

**Comment by diafour** [comment]
https://github.com/flant/kubedog/blob/master/cmd/kubedog/main.go#L39

It is a reasonable CLI default for `rollout track` mode that should not hang a CI job forever. `kubedog rollout track --timeout 0` to track forever. Werf use 0 as opts.Timeout.

**Comment by ilya-lesikov** [comment]
Default timeout for new Dynamic Tracker is 0 (infinity). Dynamic Tracker obsoletes other trackers.
